### PR TITLE
feat(policy): JWT policy

### PR DESCRIPTION
**Pull request by brasseld**
In charge of validatation of Json Web Tokens signature & expiration

Closes gravitee-io/issues#46

### CODE REVIEW

**Comment by yogeshgarg1904** [comment]
We have configured the JWT as per the below screenshot, but it is always showing unauthorized although we have valid the token online it is validating correctly. 
Please help us how can resolve the same.

Gravitee

**Comment by brasseld** [comment]
Hi @yogeshgarg1904 

I see that you've defined a JWT plan.

Do you have an application which subscribes to this plan (with the client from the token)?

**Comment by aelamrani** [comment]
@yogeshgarg1904 you specified a rsa with a HS256 signature, it is your error here

**Comment by yogeshgarg1904** [comment]
Hi @brasseld 
Can you please suggest the correct configuration

**Comment by yogeshgarg1904** [comment]
@aelamrani  what should be correct configuration

**Comment by brasseld** [comment]
@yogeshgarg1904 you have used a key to generate the token.

Please use the same hash within the `resolver parameter`

**Comment by yogeshgarg1904** [comment]
@brasseld thanks for suggestion. i have used the secret key in resolver parametre but still not working

image

**Pull request merged**
